-- Production compatibility baseline for the tables used by the current Ovona app.
-- This follows the older generation-pipeline migration so a fresh project ends
-- with the full application schema even when the original tables were created
-- manually in an earlier Supabase project.

create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text,
  avatar_url text,
  created_at timestamptz default now(),
  locale text default 'UK',
  timezone text,
  body_weight_kg numeric,
  body_fat_percent numeric,
  height_cm numeric,
  goal text,
  activity_level text,
  training_schedule jsonb,
  allergies text[] default '{}',
  dislikes text[] default '{}',
  cuisines text[] default '{}',
  pantry_staples text[] default '{}',
  household jsonb,
  delivery_preferences jsonb,
  macro_targets jsonb,
  sleep_hours numeric,
  stress_level text,
  notes text,
  updated_at timestamptz default now()
);

create table if not exists public.user_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  goal text,
  age integer,
  weight numeric,
  exercise_level text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  lifestyle text,
  cuisines text,
  allergies text,
  taste_preferences text[],
  meal_complexity text default '3',
  health_conditions text[] default '{}',
  weekly_budget numeric default 60,
  meals_per_day integer default 5,
  meal_slot_labels text[] default '{Breakfast,Snack,Lunch,Snack,Dinner}',
  target_calories numeric,
  target_protein numeric,
  target_carbs numeric,
  target_fat numeric,
  max_prep_minutes integer,
  dietary_mode text,
  cuisine_preferences text[]
);

create unique index if not exists user_preferences_user_id_key
  on public.user_preferences(user_id);

create table if not exists public.user_allergies (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  allergy_name text not null,
  severity text default 'moderate'
);

create index if not exists user_allergies_user_id_idx
  on public.user_allergies(user_id);

create table if not exists public.meal_plans (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  name text not null,
  week_start_date date,
  total_calories integer,
  created_at timestamptz default now(),
  plan_json jsonb,
  normalized_items jsonb
);

create unique index if not exists meal_plans_user_week_start_key
  on public.meal_plans(user_id, week_start_date);

create table if not exists public.meal_logs (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references auth.users(id) on delete cascade,
  meal_instance_id text not null,
  date date not null,
  status text not null check (status in ('planned', 'eaten', 'skipped', 'swapped')),
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create unique index if not exists meal_logs_user_instance_date_key
  on public.meal_logs(user_id, meal_instance_id, date);

create table if not exists public.plan_history (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade,
  plan_id text not null,
  day_id text not null,
  date date not null,
  week_start date not null,
  meals jsonb not null,
  created_at timestamptz default now()
);

create index if not exists plan_history_user_week_day_idx
  on public.plan_history(user_id, week_start, day_id, created_at desc);

create table if not exists public.ingredients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  avg_piece_grams numeric,
  category text not null default 'Other',
  per_100g_calories numeric not null default 0,
  per_100g_protein numeric not null default 0,
  per_100g_carbs numeric not null default 0,
  per_100g_fat numeric not null default 0,
  per_100g_fibre numeric not null default 0,
  per_100g_iron_mg numeric,
  per_100g_omega_3_g numeric,
  per_100g_b12_mcg numeric,
  per_100g_vitamin_d_mcg numeric,
  per_100g_folate_mcg numeric,
  per_100g_calcium_mg numeric,
  unit_type text not null default 'weight',
  default_unit text not null default 'g',
  allergens text[] not null default '{}',
  dietary_flags text[] not null default '{}',
  omega_3_g numeric default 0,
  iron_mg numeric default 0,
  b12_mcg numeric default 0,
  vitamin_c_mg numeric default 0,
  vitamin_d_mcg numeric default 0,
  calcium_mg numeric default 0,
  zinc_mg numeric default 0,
  magnesium_mg numeric default 0,
  potassium_mg numeric default 0,
  folate_mcg numeric default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  verified boolean not null default true,
  source text not null default 'manual'
);

alter table public.meal_concepts
  add column if not exists description text,
  add column if not exists times_planned integer not null default 0,
  add column if not exists times_eaten integer not null default 0,
  add column if not exists times_swapped integer not null default 0,
  add column if not exists times_skipped integer not null default 0;

alter table public.user_preferences
  add column if not exists max_prep_minutes integer,
  add column if not exists dietary_mode text,
  add column if not exists cuisine_preferences text[];

alter table public.ingredients
  add column if not exists per_100g_iron_mg numeric,
  add column if not exists per_100g_omega_3_g numeric,
  add column if not exists per_100g_b12_mcg numeric,
  add column if not exists per_100g_vitamin_d_mcg numeric,
  add column if not exists per_100g_folate_mcg numeric,
  add column if not exists per_100g_calcium_mg numeric,
  add column if not exists per_100g_fibre numeric,
  add column if not exists verified boolean not null default true,
  add column if not exists source text not null default 'manual';
